import { Input } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { io } from 'socket.io-client'

const Home: NextPage = () => {
  const [text, setText] = useState('')

  useEffect(() => {
    const socket = io();
    const socketInitializer = async () => {
      await fetch('/api/socket');
  
      socket.on('connect', () => {
        console.log('connected')
      })
    }
    
    socketInitializer();

    () => { socket.off() }
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-red-500'>HOME</div>
      <Input 
        value={text}
        onChange={e => setText(e.target.value)}
      />
    </div>
  )
}

export default Home;
